name: Release on GitHub & PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "${{ matrix.python-version }} ${{ matrix.os }} ${{ matrix.arch }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["cp38-*", "cp39-*", "cp310-*", "cp311-*"]
        arch: ["x86_64", "aarch64"]
        exclude:
          - arch: "aarch64"
            os: "macos-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Set up QEMU
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - run: python -m pip install -U pip
      - run: python -m pip install cibuildwheel
      - run: python -m cibuildwheel --output-dir wh
        env:
          CIBW_BUILD: ${{ matrix.python-version }}
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_SKIP: "*-musllinux_aarch64"
          CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux_2_28_x86_64"
          CIBW_MANYLINUX_AARCH64_IMAGE: "quay.io/pypa/manylinux_2_28_aarch64"
          CIBW_REPAIR_WHEEL_COMMAND: ""
          CIBW_ENVIRONMENT: CMEEL_LOG_LEVEL="DEBUG"
      - uses: actions/upload-artifact@v3
        with:
          path: wh

  release:
    needs: ["build"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/download-artifact@v3
      - run: ls artifact
      - run: python -m pip install twine
      - run: python -m twine upload -u __token__ -p "${{ secrets.PYPI_TOKEN }}" artifact/master_board*.whl
      - run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - run: gh release create -t "Release ${{ env.TAG }}" -n "Release ${{ env.TAG }}" ${{ env.TAG }} artifact/odri_control_interface*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
