name: Check SDK wheel

on: ["push", "pull_request"]

env:
  CMEEL_LOG_LEVEL: DEBUG

jobs:
  build:
    name: Build ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: setup
        run: |
          python -m pip install -U pip
          python -m pip install wheel
      - name: build cmeel wheel
        run: python -m pip wheel -vw wh .
      - uses: actions/upload-artifact@v3
        with:
          path: wh

  test:
    needs: ["build"]
    name: Test ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        exclude:
          - os: "macos-latest"
            python-version: "3.8"
    steps:
      - uses: actions/download-artifact@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup
        run: |
          python -m pip install -U pip
          python -m pip install wheel simple503
          python -m simple503 --sort --base-url "${{ github.workspace }}/artifact" artifact
          python -m pip install -U pip
      - name: install wheel
        run: python -m pip install -i "file:///${{ github.workspace }}/artifact" odri-control-interface
      - name: test module
        if: matrix.os == 'ubuntu-latest'
        run: >
          python -c "import libodri_control_interface_pywrap;
          assert libodri_control_interface_pywrap.CalibrationMethod.negative == 2"
        env:
          PYTHONWARNINGS: error
